### ISSUE TITLE
ChainUnknownError: Unknown chain id: 10

### ISSUE THREAD

**Issue by 1mdc** [aragon/use-wallet#178]
I have this error when connecting to optimism mainnet which has chain id=10. Properly chains.js needs to be updated?

Thanks.

**Comment by WissenIstNacht** [comment]
Hello :wave:

Sorry for the delay. Could you tell me a bit more about this error?

**Comment by panukettu** [comment]
As I see it there is no fallback when the chain does not exist in chains.js, I think it could be considered to have a fallback for this. Can most likely make a PR about this later.

**Comment by 1mdc** [comment]
@WissenIstNacht The error is in the title when connecting to an unknown chain Id.

@panukettu Yes, that would resolve this issue. thank you.

**Comment by WissenIstNacht** [comment]
Hey there, thanks for responding.

In hindsight, throwing an error in this way might be too much. We did this to encourage consistency across our projects. I will make an adjustment to the existing code s.t. it returns an object populated with 'unknown' if the chain is not in the list of chain.

**Comment by ihorbond** [comment]
@WissenIstNacht yes it should have a fallback please. Otherwise can't test locally with hardhat and chainId 31337

**Comment by keon** [comment]
any work around on this one?
It is hard to use this lib in production b/c of this error

**Comment by WissenIstNacht** [comment]
This should be fixed with the next release. You should again be able to use any chain you want, without it needing to be in `chain.ts`. 

The drawback is that, now, the context no longer exposes `networkName`. If you want this, you'll have to either: Add it to `chain.ts` via a PR (much appreciated!), or manage that information yourself.

I'm closing this now. Have a nice week 🙂
